/*
 * ScalaRay - Ray tracer based on pbrt (see http://pbrt.org) written in Scala 2.8
 * Copyright (C) 2009, 2010  Jesper de Jong
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.jesperdj.scalaray.sampler

import scala.collection.immutable.{ IndexedSeq, Stream, Traversable }

import org.jesperdj.scalaray.raster.Rectangle

// TODO: The solution here with SampleStream looks nice, but might be the cause of a memory problem.
// Especially when you have area light sources with > 20 samples per ray, ScalaRay eats up enormous amounts of memory (almost 2 GB for a simple scene).
// I suspect that this is because the Stream remembers all elements that are in it. That's not necessary; once a Sample has been enumerated, it doesn't
// need to be remembered by the sampler.

// Sampler that generates samples for one pixel at a time
abstract class PixelSampler (rectangle: Rectangle, samplesPerPixel: Int) extends Sampler(rectangle, samplesPerPixel) {
	// The samples generated by this sampler
	val samples: Traversable[Sample] = new SampleStream(rectangle.left, rectangle.top, 0, generateSamples(rectangle.left, rectangle.top))

	// Split the sampler into a number of sub-samplers (for multiprocessing)
	// Overridden to restrict return type from Traversable[Sampler] to Traversable[PixelSampler]
	def split(count: Int): Traversable[PixelSampler]

	// Stream to generate samples
	private final class SampleStream (x: Int, y: Int, index: Int, pixelSamples: IndexedSeq[Sample]) extends Stream[Sample] {
		def tailDefined = false

		override def isEmpty = y > rectangle.bottom

		override def head = pixelSamples(index)

		override def tail = {
			var xx = x; var yy = y; var ii = index + 1
			var ps = pixelSamples

			if (ii >= samplesPerPixel) {
				ii = 0; xx += 1
				if (xx > rectangle.right) { xx = rectangle.left; yy += 1 }
				if (yy <= rectangle.bottom) { ps = generateSamples(xx, yy) }
			}

			if (yy <= rectangle.bottom) new SampleStream(xx, yy, ii, ps) else Stream.Empty
		}
	}

	// Generate samples for one pixel
	protected def generateSamples(x: Int, y: Int): IndexedSeq[Sample]
}
