/*
 * ScalaRay - Ray tracer based on pbrt (see http://pbrt.org) written in Scala 2.8
 * Copyright (C) 2009, 2010  Jesper de Jong
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.jesperdj.scalaray.sampler

import scala.collection.immutable.Traversable

import org.jesperdj.scalaray.raster.Rectangle

// Sampler (pbrt 7.2)
abstract class Sampler (val rectangle: Rectangle, val samplesPerPixel: Int) {
	// The samples generated by this sampler
	val samples: Traversable[Sample]
}

// Sampler factory
abstract class SamplerFactory {
	// Create a set of related samplers that together cover the full domain to be sampled
	def createSamplers(count: Int): Traversable[Sampler]
}
